services:
  # Application A
  appa:
    build:
      context: .
      dockerfile: docker/appA.Dockerfile
    command: gunicorn --bind 0.0.0.0:5005 "app:create_app()"
    networks:
      - appa_net
      - proxy_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  appa-proxy:
    build:
      context: .
      dockerfile: docker/envoy.Dockerfile
    volumes:
      - ./envoy/appA/proxy.yaml:/etc/envoy/envoy.yaml
      - ./logs/appa/proxy:/var/log/envoy
    networks:
      - appa_net
      - proxy_net
    depends_on:
      appa:
        condition: service_healthy
    ports:
      - "9906:9906"    # Only expose admin port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9906/ready"]
      interval: 10s
      timeout: 5s
      retries: 3

  appa-ingress:
    build:
      context: .
      dockerfile: docker/envoy.Dockerfile
    volumes:
      - ./envoy/appA/ingress.yaml:/etc/envoy/envoy.yaml
      - ./logs/appa/ingress:/var/log/envoy
    ports:
      - "8080:8080"
      - "9901:9901"    # AppA ingress admin
    networks:
      - proxy_net
    depends_on:
      appa:
        condition: service_healthy
      appa-proxy:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9901/ready"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Application B
  appb:
    build:
      context: .
      dockerfile: docker/appB.Dockerfile
    command: gunicorn --bind 0.0.0.0:5001 "app:create_app()"
    networks:
      - appb_net
      - proxy_net
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - TARGET_APP_URL=http://appa-proxy:9902
    volumes:
      - ./src/appB/app:/app/app
    depends_on:
      appa:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/check/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  appb-proxy:
    build:
      context: .
      dockerfile: docker/envoy.Dockerfile
    volumes:
      - ./envoy/appB/proxy.yaml:/etc/envoy/envoy.yaml
      - ./logs/appb/proxy:/var/log/envoy
    ports:
      - "9904:9904"    # Only expose admin port
    networks:
      - appb_net
      - proxy_net
    depends_on:
      appb:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9904/ready"]
      interval: 5s
      timeout: 2s
      retries: 3

  appb-ingress:
    build:
      context: .
      dockerfile: docker/envoy.Dockerfile
    volumes:
      - ./envoy/appB/ingress.yaml:/etc/envoy/envoy.yaml
      - ./logs/appb/ingress:/var/log/envoy
    ports:
      - "8081:8080"
      - "9903:9903"    # AppB ingress admin
    networks:
      - proxy_net
    depends_on:
      appb:
        condition: service_started
      appb-proxy:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9903/ready"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  appa_net:    # Private network for AppA and its proxy
    internal: true
  appb_net:    # Private network for AppB and its proxy
    internal: true
  proxy_net:   # Shared network for proxies to communicate 